### ISSUE TITLE
Mac OS X 10.11.6: chapter markers does not work

### ISSUE THREAD

**Issue by ragetman** [davidschlachter/itunes-concatenator#19]
Track Concatenator version 2.4 (8), Mac OS X 10.11.6 and iTunes 12.5.1.21, filetypes is .m4a and .mp3, option "TOC to Lyrics tag" selected.
After finishing track merge process in Lyrics tab all songs have same start time - 00:00:00.000 and in iTunes chapters menu displayed only one chapter name.
If you still support this program, please, help to solve problem...
Many thanks!

**Comment by davidschlachter** [comment]
I'll take a look at it this week and see if I can replicate the issue — I haven't used the tool for a few months  :)

**Comment by ragetman** [comment]
...there is no hope?

**Comment by davidschlachter** [comment]
Sorry for the late reply! I took a look at this today and merged several tracks, but I couldn't replicate this issue with the chapters.

Perhaps the packages that the program depends on are out of date? To update them, open a Terminal and use the command `brew update ; brew upgrade ; brew cleanup`

It could also be the specific files that you're trying to merge (do other files merge without problems with the chapters?). 

![capture d ecran 2016-10-25 a 08 14 15](https://cloud.githubusercontent.com/assets/8271268/19753245/0cc9c9ec-9bd1-11e6-8056-bfdad091a66a.png)

**Comment by ragetman** [comment]
Problem solved...
After executing the command `brew update ; brew upgrade ; brew cleanup` still miraculously worked.
Thank you very much, wonderful app.

**Comment by davidschlachter** [comment]
Happy to hear it! Thanks for your patience.
