### ISSUE TITLE
Does the opposite of this project exist?

### ISSUE THREAD

**Issue by pirate** [davidschlachter/itunes-concatenator#24]
I mostly want to split tracks up, not join them together.

I have many 1+hr long mixes with tons of great, unshazamable, only-mixed-once-live subtracks buried in the middle of them that I'd like to split out into separate tracks. In your journey developing this project, have you found any alternatives that do the opposite?

Thanks! Feel free to close this ticket to keep your bug tracker clean as it's not a real issue/bug report, just a question.

**Comment by davidschlachter** [comment]
I don't know of an automated way to do this, just using generic audio editing tools. For example, I've used [Fission](https://rogueamoeba.com/fission/) -- it's a GUI audio editor that's sort of like Audacity but Mac-native.

You can also use FFMPEG (installable with Homebrew). For example, with a file 'songs.m4a', to extract the audio from 2:32 (i.e. 152 seconds) to 6:02 (362 s), you'd use a command of the form: `ffmpeg -i /path/to/songs.m4a -ss 152 -t $((362-152)) -c:a copy extracted-song.m4a`.

Good luck!
